on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}
  BUNDLE_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/bundle

jobs:
  build-bundle:
    runs-on: [self-hosted]
    strategy:
      matrix:
        host-tag: [ltsc2019]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          .\build-bundle.ps1 `
            -HostTag ${{ matrix.host-tag }} `
            -ImageName ${env:BUNDLE_IMAGE_NAME} `
            --isolation=hyperv
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: sunghwan2789
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          $bundle = Get-Content .\bundle.json | ConvertFrom-Json
          foreach ($item in $bundle.items) {
            docker push ('{0}:{1}-${{ matrix.host-tag }}' -f $env:BUNDLE_IMAGE_NAME, $item.name)
          }
  build:
    needs: build-bundle
    runs-on: [self-hosted]
    strategy:
      matrix:
        os: [nanoserver, windowsservercore]
        host-tag: [ltsc2016, 1607, 1709, 1803, ltsc2019, 1809]
        # not supported on GitHub-hosted runners
        # * 1607, 1709, 1803, 1903, 1909
        exclude:
          - os: nanoserver
            host-tag: ltsc2016
          - os: nanoserver
            host-tag: 1607
          - os: nanoserver
            host-tag: ltsc2019
        include:
          - host-tag: ltsc2016
            bundle-tag: ltsc2019
          - host-tag: 1607
            bundle-tag: ltsc2019
          - host-tag: 1709
            bundle-tag: ltsc2019
          - host-tag: 1803
            bundle-tag: ltsc2019
          - host-tag: ltsc2019
            bundle-tag: ltsc2019
          - host-tag: 1809
            bundle-tag: ltsc2019
    env:
      IMAGE_TAG: ${{ matrix.os }}-${{ matrix.host-tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          .\build-server.ps1 `
            -HostImageName ${{ matrix.os }} `
            -HostTag ${{ matrix.host-tag }} `
            -ImageName $env:IMAGE_NAME `
            -BundleImageName $env:BUNDLE_IMAGE_NAME `
            -BundleTag ${{ matrix.bundle-tag }} `
            --pull --isolation=hyperv
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: sunghwan2789
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
      - name: Push image
        run: |
          docker push ('{0}:{1}' -f $env:IMAGE_NAME, $env:IMAGE_TAG)
  # TODO: latest tag support
  # manifest:
  #   needs: build
  #   runs-on: windows-latest
  #   steps:
  #     - run: |
  #         docker manifest create
