on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 9 * * *'

env:
  IMAGE_NAME: sunghwan2789/minecraft-server

jobs:
  build-bundle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2016]
        include:
          - os: windows-2019
            host-tag: ltsc2019
          - os: windows-2016
            host-tag: ltsc2016
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          .\build-bundle.ps1 `
            -HostTag ${{ matrix.host-tag }} `
            -ImageName docker.pkg.github.com/${{ github.repository }}/bundle
      - name: Push image
        run: |
          docker login -u sunghwan2789 -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          $bundle = Get-Content .\bundle.json | ConvertFrom-Json; `
            foreach ($item in $bundle.items) { `
              $name = '{0}' -f $item.name; `
              docker push docker.pkg.github.com/${{ github.repository }}/bundle:$name-${{ matrix.host-tag }}; `
            }
  # build:
  #   runs-on: windows-2019
  #   strategy:
  #     matrix:
  #       os: [nanoserver]
  #       version: [1809]
  #       # not supported on GitHub-hosted runners
  #       # * 1607, 1709, 1803, 1903, 1909
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build image
  #       run: |
  #         docker build `
  #           -t ${env:IMAGE_NAME}:${{ matrix.os }}-${{ matrix.version }} `
  #           --build-arg VARIANT=6.2.4-${{ matrix.os }}-${{ matrix.version }} `
  #           .
  #     - name: Push image.
  #       run: |
  #         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #         docker push ${env:IMAGE_NAME}:${{ matrix.os }}-${{ matrix.version }}
  # TODO: latest tag support
  # manifest:
  #   needs: build
  #   runs-on: windows-latest
  #   steps:
  #     - run: |
  #         docker manifest create
